import { Tooltip } from "@cosmos-ui/vue";
import MarkdownIt from "markdown-it";
import Card from "./global-components/Card.vue";
import CardBanner from "./global-components/CardBanner.vue";
import CardLinks from "./global-components/CardLinks.vue";
import CardModule from "./global-components/CardModule.vue";
import CustomHeader from "./global-components/CustomHeader.vue";
import FeedbackBox from "./global-components/FeedbackBox.vue";
import Homepage from "./global-components/Homepage.vue";
import IconArrow from "./global-components/IconArrow.vue";
import IconCircleCross from "./global-components/IconCircleCross.vue";
import IconMenu from "./global-components/IconMenu.vue";
import IconSearch from "./global-components/IconSearch.vue";
import IconSpaceship from "./global-components/IconSpaceship.vue";
import IconWindow from "./global-components/IconWindow.vue";
import ImageLetter from "./global-components/ImageLetter.vue";
import LayoutDefault from "./global-components/LayoutDefault.vue";
import LogoCore from "./global-components/LogoCore.vue";
import LogoCoreText from "./global-components/LogoCoreText.vue";
import LogoHub from "./global-components/LogoHub.vue";
import LogoHubText from "./global-components/LogoHubText.vue";
import LogoSdk from "./global-components/LogoSdk.vue";
import LogoSdkText from "./global-components/LogoSdkText.vue";
import Resource from "./global-components/Resource.vue";
import SearchBar from "./global-components/SearchBar.vue";
import SectionSearch from "./global-components/SectionSearch.vue";
import Tag from "./global-components/Tag.vue";
import TmAside from "./global-components/TmAside.vue";
import TmBreadcrumbs from "./global-components/TmBreadcrumbs.vue";
import TmCodeBlock from "./global-components/TmCodeBlock.vue";
import TmContentCards from "./global-components/TmContentCards.vue";
import TmFaq from "./global-components/TmFaq.vue";
import TmFooter from "./global-components/TmFooter.vue";
import TmFooterLinks from "./global-components/TmFooterLinks.vue";
import TmHelpSupport from "./global-components/TmHelpSupport.vue";
import TmIconBasics from "./global-components/TmIconBasics.vue";
import TmIconCore from "./global-components/TmIconCore.vue";
import TmIconDash from "./global-components/TmIconDash.vue";
import TmIconEdit from "./global-components/TmIconEdit.vue";
import TmIconHex from "./global-components/TmIconHex.vue";
import TmIconInterfaces from "./global-components/TmIconInterfaces.vue";
import TmIconIntroduction from "./global-components/TmIconIntroduction.vue";
import TmIconMenu from "./global-components/TmIconMenu.vue";
import TmIconModules from "./global-components/TmIconModules.vue";
import TmIconOutbound from "./global-components/TmIconOutbound.vue";
import TmIconPaperPen from "./global-components/TmIconPaperPen.vue";
import TmIconSpecifications from "./global-components/TmIconSpecifications.vue";
import TmImage from "./global-components/TmImage.vue";
import TmLogoChat from "./global-components/TmLogoChat.vue";
import TmLogoCore from "./global-components/TmLogoCore.vue";
import TmLogoCosmos from "./global-components/TmLogoCosmos.vue";
import TmLogoHub from "./global-components/TmLogoHub.vue";
import TmLogoIbc from "./global-components/TmLogoIbc.vue";
import TmLogoSdk from "./global-components/TmLogoSdk.vue";
import TmLogoTendermint from "./global-components/TmLogoTendermint.vue";
import TmModeSwitch from "./global-components/TmModeSwitch.vue";
import TmNewsletterForm from "./global-components/TmNewsletterForm.vue";
import TmSearch from "./global-components/TmSearch.vue";
import TmSelectLanguage from "./global-components/TmSelectLanguage.vue";
import TmSelectVersion from "./global-components/TmSelectVersion.vue";
import TmSidebar from "./global-components/TmSidebar.vue";
import TmSidebarContent from "./global-components/TmSidebarContent.vue";
import TmSidebarTree from "./global-components/TmSidebarTree.vue";
import TmTocMenu from "./global-components/TmTocMenu.vue";
import TmTopBanner from "./global-components/TmTopBanner.vue";
import TmTopBar from "./global-components/TmTopBar.vue";

export default ({ Vue }) => {
  Vue.component("df", Tooltip);
  Vue.component("card", Card);
  Vue.component("card-banner", CardBanner);
  Vue.component("card-links", CardLinks);
  Vue.component("card-module", CardModule);
  Vue.component("custom-header", CustomHeader);
  Vue.component("feedback-box", FeedbackBox);
  Vue.component("homepage", Homepage);
  Vue.component("icon-arrow", IconArrow);
  Vue.component("icon-circle-cross", IconCircleCross);
  Vue.component("icon-menu", IconMenu);
  Vue.component("icon-search", IconSearch);
  Vue.component("icon-spaceship", IconSpaceship);
  Vue.component("icon-window", IconWindow);
  Vue.component("image-letter", ImageLetter);
  Vue.component("layout-default", LayoutDefault);
  Vue.component("logo-core", LogoCore);
  Vue.component("logo-core-text", LogoCoreText);
  Vue.component("logo-hub", LogoHub);
  Vue.component("logo-hub-text", LogoHubText);
  Vue.component("logo-sdk", LogoSdk);
  Vue.component("logo-sdk-text", LogoSdkText);
  Vue.component("resource", Resource);
  Vue.component("search-bar", SearchBar);
  Vue.component("section-search", SectionSearch);
  Vue.component("tag", Tag);
  Vue.component("tm-aside", TmAside);
  Vue.component("tm-breadcrumbs", TmBreadcrumbs);
  Vue.component("tm-code-block", TmCodeBlock);
  Vue.component("tm-content-cards", TmContentCards);
  Vue.component("tm-faq", TmFaq);
  Vue.component("tm-footer", TmFooter);
  Vue.component("tm-footer-links", TmFooterLinks);
  Vue.component("tm-help-support", TmHelpSupport);
  Vue.component("tm-icon-basics", TmIconBasics);
  Vue.component("tm-icon-core", TmIconCore);
  Vue.component("tm-icon-dash", TmIconDash);
  Vue.component("tm-icon-edit", TmIconEdit);
  Vue.component("tm-icon-hex", TmIconHex);
  Vue.component("tm-icon-interfaces", TmIconInterfaces);
  Vue.component("tm-icon-introduction", TmIconIntroduction);
  Vue.component("tm-icon-menu", TmIconMenu);
  Vue.component("tm-icon-modules", TmIconModules);
  Vue.component("tm-icon-outbound", TmIconOutbound);
  Vue.component("tm-icon-paper-pen", TmIconPaperPen);
  Vue.component("tm-icon-specifications", TmIconSpecifications);
  Vue.component("tm-image", TmImage);
  Vue.component("tm-logo-chat", TmLogoChat);
  Vue.component("tm-logo-core", TmLogoCore);
  Vue.component("tm-logo-cosmos", TmLogoCosmos);
  Vue.component("tm-logo-hub", TmLogoHub);
  Vue.component("tm-logo-ibc", TmLogoIbc);
  Vue.component("tm-logo-sdk", TmLogoSdk);
  Vue.component("tm-logo-tendermint", TmLogoTendermint);
  Vue.component("tm-mode-switch", TmModeSwitch);
  Vue.component("tm-newsletter-form", TmNewsletterForm);
  Vue.component("tm-search", TmSearch);
  Vue.component("tm-select-language", TmSelectLanguage);
  Vue.component("tm-select-version", TmSelectVersion);
  Vue.component("tm-sidebar", TmSidebar);
  Vue.component("tm-sidebar-content", TmSidebarContent);
  Vue.component("tm-sidebar-tree", TmSidebarTree);
  Vue.component("tm-toc-menu", TmTocMenu);
  Vue.component("tm-top-banner", TmTopBanner);
  Vue.component("tm-top-bar", TmTopBar);

  Vue.mixin({
    methods: {
      md: string => {
        const md = new MarkdownIt({ html: true, linkify: true });
        return `<div>${md.renderInline(string)}</div>`;
      },
    }
  })
  require("./styles/palette.styl");
};